### ISSUE TITLE
Using this in a pipeline

### ISSUE THREAD

**Issue by Shashi456** [epwalsh/nlp-models#36]
Hello, 
I'm sorta asking for your help. I need to train this model in a pipeline structure, where in i have some outputs from some other model feeding into this, How could i go about doing that? and implementing a custom loss for this model?

Also, would it be possible to extend this to pointer generator somehow?

**Comment by epwalsh** [comment]
Hi @Shashi456 sorry I missed this! Did you figure it out or do you still need some guidance?

**Comment by Shashi456** [comment]
@epwalsh I did help, but I figured it out with some other model somehow. I just really really liked this implementation. I'll ask you if I have any doubts

**Comment by epwalsh** [comment]
@Shashi456 sounds good! Glad you figured it out.
